name:                Zertz
version:             0.1.0.0
github:              "githubuser/Zertz"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Zertz#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- hashable
- ansi-terminal
- lens
- base-unicode-symbols
- sdl2
- sdl2-image
- text
- extra
- monad-loops
- linear
- NumInstances
- StateVar

library:
  source-dirs: src

executables:
  Zertz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Zertz

tests:
  Zertz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Zertz
